spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
    deserialization:
      accept_float_as_int: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  flyway:
    locations: classpath:/db/migration
    out-of-order: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enable: true

opentracing:
  jaeger:
    enabled: false
  spring:
    web:
      enabled: false
      client:
        enabled: false
    cloud:
      scheduled:
        enabled: false
      async:
        enabled: false
      log:
        enabled: false
