spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
    deserialization:
      accept_float_as_int: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  datasource:
    url: jdbc:mysql://localhost:3306/report
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  flyway:
    locations: classpath:/db/migration
    out-of-order: false
