#!/usr/bin/env ruby

COMMIT_MSG_MAX_LENGTH = 141
COMMIT_FORMAT_POLICY_TAG = "[COMMIT_FORMAT_POLICY] ERROR::"
COMMIT_ERROR_BANNER = "=============================================================================="
$COMMIT_FORMAT_REGEX = /^(chore|docs|feat|fix|refactor|style|test)\: [\sA-z0-9\-\.,_\"]+$/

message_file = ARGV[0]
message = File.read(message_file)

if message.include? "This reverts commit"
  exit 0
end

if message.include? "It looks like you may be committing a cherry-pick"
  exit 0
end

if message.start_with? "Merge branch"
  exit 0
end

if message.length > COMMIT_MSG_MAX_LENGTH
  puts COMMIT_ERROR_BANNER
  puts "#{COMMIT_FORMAT_POLICY_TAG} Commit message length #{message.length} exceeds the maximum allowed length: #{COMMIT_MSG_MAX_LENGTH}."
  puts COMMIT_ERROR_BANNER
  exit 1
end

if !$COMMIT_FORMAT_REGEX.match(message)
  puts COMMIT_ERROR_BANNER
  puts "Hey commit message should be like (feat: massive fish)\n"
  puts COMMIT_ERROR_BANNER
  exit 1
end

